version: '3'

services:
  postgresql:
    image: postgres
    container_name: nestjs
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
      - POSTGRES_DATABASE=nestjs
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-nestjs
    ports:
      - '6379-6379'